[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pumpstake = "GX3a35f4jkcoZCzxqwGyr4ryRch2dhC3Fe8SoEb6fg8S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"
